Add `./configure --enable-dkms`
The `./configure --enable-dkms` flag enables a DKMS configuration to
dynamically build whatever RT NIC modules are available for a kernel.

The flag sets up `Kbuild` to be configurable from the `make modules`
command line.  For example, running `./configure --enable-r8152` will
template `devices/Kbuild.in`, normally replacing `@ENABLE_R8152@` with
`1` (`--disable-r8152` replaces that with `0`).  The `--enable-dkms`
flag instead replaces it with `$(ENABLE_R8152)`.  The DKMS
configuration is simply a `bash` shell script, so the check for
whether a matching `devices/r8152-$(KVER)-ethercat.c` exists can be
performed there, and if so, enable the build in the `make modules
ENABLE_R8152=1` command line.

diff --git a/Makefile.kbuild b/Makefile.kbuild
--- a/Makefile.kbuild
+++ b/Makefile.kbuild
@@ -7,9 +7,21 @@ KBUILD = $(MAKE) -C "$(LINUX_SOURCE_DIR)" M="$(abs_srcdir)" INSTALL_MOD_DIR="$(I
 
 
 modules:
+	@if test -z "$(LINUX_SOURCE_DIR)"; then \
+	    echo "ERROR:  LINUX_SOURCE_DIR unset" >&2; \
+	    echo "ERROR:  Add configure options to build/install modules?" >&2; \
+	    echo "ERROR:  ./configure --enable-kernel --with-linux-dir=[...]" >&2; \
+	    exit 1; \
+	fi
 	$(KBUILD) modules
 
 modules_install:
+	@if test -z "$(LINUX_SOURCE_DIR)"; then \
+	    echo "ERROR:  LINUX_SOURCE_DIR unset" >&2; \
+	    echo "ERROR:  Add configure options to build/install modules?" >&2; \
+	    echo "ERROR:  ./configure --enable-kernel --with-linux-dir=[...]" >&2; \
+	    exit 1; \
+	fi
 	$(KBUILD) modules_install
 
 
